---

- hosts: nginx
  become: true
  tasks: 


  - name: install simple packages
    tags: apache,apache2,ubuntu
    apt:  
      name:
       - vim-nox
       - apache2
       - libapache2-mod-php
      state= latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "ubuntu"]


  - name: install simple packages
    tags: apache,centos,httpd
    dnf:
      name:
        - vim-nox
        - httpd
        - php
      state= latest
      update_cache= yes
    when: ansible_distribution == "Centos"
