---

- hosts: nginx
  become: true
  tasks: 

  - name: update repository index
    apt:
      update_cache: yes
      state= latest

  - name: install vim-nox package
    apt:  
      name: vim-nox
      state= latest
